using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;
using FMODUnity;
using UnityEditor;
using UnityEngine;

namespace Framework.Editor
{
    [Serializable]
    public sealed class FMODEditor : AssetPostprocessor
    {
        private const string EventPrefix = "event:/";
        private const string SnapshotPrefix = "snapshot:/";

        private static bool _generating = false;

        private void OnPreprocessAsset()
        {
            // .bytes
            if (assetPath.EndsWith(".bytes") && assetPath.Contains("FMODBanks"))
            {
                // 生成事件常量类
                GenerateEventConstClass();
            }
        }
        
        [Sirenix.OdinInspector.Button("GenerateEventConstClass")]
        private static async void GenerateEventConstClass()
        {
            if (_generating)
            {
                return;
            }

            var all = GetAllEventRef();
            _generating = true;
            await GenerateEventConstClassAsync(all);
            _generating = false;
            AssetDatabase.Refresh();
        }


        private static Task GenerateEventConstClassAsync(List<EditorEventRef> eventRefs)
        {
            string targetPath = "Assets/Game/Global/Generation/FMODName.cs";
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("/*Auto-generated by FMODEditor*/");
            sb.AppendLine("namespace FMOD");
            sb.AppendLine("{");
            sb.AppendLine("    public static class FMODName");
            sb.AppendLine("    {");
            // #region Event
            sb.AppendLine("        public static class Event");
            sb.AppendLine("        {");
            foreach (var eventRef in eventRefs)
            {
                if (!eventRef.Path.StartsWith(EventPrefix))
                {
                    continue;
                }

                sb.AppendLine();
                // 移除前缀
                string eventName = eventRef.Path.Substring(EventPrefix.Length);
                eventName = ProcessString(eventName);
                sb.AppendLine($"        \tpublic const string {eventName} = \"{eventRef.Path}\";");
                if(eventRef.Parameters.Count == 0)
                    continue;
                
                foreach (var eventRefParameter in eventRef.Parameters)
                {
                    sb.AppendLine($"\t\t\t/// <summary>");
                    sb.AppendLine($"\t\t\t/// {eventRefParameter.Name}");
                    sb.AppendLine($"\t\t\t/// </summary>");
                    string parameterName = ProcessString(eventRefParameter.Name);
                    sb.AppendLine(
                        $"        \tpublic const string {eventName}_{parameterName} = \"{eventRefParameter.Name}\";");
                }
            }

            sb.AppendLine("        }");
            // #endregion
            // #region Snapshot
            sb.AppendLine("        public static class Snapshot");
            sb.AppendLine("        {");
            foreach (var eventRef in eventRefs)
            {
                if (!eventRef.Path.StartsWith(SnapshotPrefix))
                {
                    continue;
                }

                // 移除前缀
                string snapshotName = eventRef.Path.Substring(SnapshotPrefix.Length);
                sb.AppendLine($"        \tpublic const string {snapshotName} = \"{eventRef.Path}\";");
            }

            sb.AppendLine("        }");
            // #endregion
            // #region Bank
            sb.AppendLine("        public static class Bank");
            sb.AppendLine("        {");
            foreach (var editorBankRef in EventManager.Banks)
            {
                string bankName = editorBankRef.Name;
                // 替换. 为_
                bankName = ProcessString(bankName);
                sb.AppendLine($"        \tpublic const string {bankName} = \"{editorBankRef.StudioPath}\";");
            }

            sb.AppendLine("        }");
            // #endregion
            // #region Parameter
            sb.AppendLine("        public static class GlobalParameter");
            sb.AppendLine("        {");
            foreach (var editorParamRef in EventManager.Parameters)
            {
                sb.AppendLine(
                    $"        \tpublic const string {editorParamRef.Name} = \"{editorParamRef.StudioPath}\";");
            }

            sb.AppendLine("        }");
            // #endregionGetStableHashCode

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return System.IO.File.WriteAllTextAsync(targetPath, sb.ToString());
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        private static string ProcessString(string str)
        {
            // 转utf8
            str = Encoding.UTF8.GetString(Encoding.Default.GetBytes(str));
            // 正则表达式只拿数字和字母 中间的其他字符换成_
            return System.Text.RegularExpressions.Regex.Replace(str, "[^0-9a-zA-Z]", "_");
        }

        private static List<EditorEventRef> GetAllEventRef()
        {
            List<EditorEventRef> refs = new List<EditorEventRef>();
            var start = EventManager.Events.GetEnumerator();
            var current = start.Current;
            refs.Add(current);
            while (start.MoveNext())
            {
                current = start.Current;
                refs.Add(current);
            }

            refs.RemoveAll(r => r == null);


            return refs;
        }
    }
}