/*Auto-generated by FMODEditor*/
namespace FMOD
{
    public static class FMODName
    {
        public static class Event
        {

        	public const string SFX_coin_recieved_230517 = "event:/SFX/coin-recieved-230517";

        	public const string SFX_energy_drink_effect_230559 = "event:/SFX/energy-drink-effect-230559";

        	public const string BGM_first_step = "event:/BGM/first_step";

        	public const string BGM_game_home = "event:/BGM/game_home";

        	public const string SFX_plant_grow = "event:/SFX/plant_grow";

        	public const string SFX_purchase_succesful_ingame_230550 = "event:/SFX/purchase-succesful-ingame-230550";
        }
        public static class Snapshot
        {
        }
        public static class Bank
        {
        	public const string Master_strings = "bank:/Master.strings";
        	public const string Master = "bank:/Master";
        }
        public static class GlobalParameter
        {
        }
    }
}
