
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BuffConfig : Luban.BeanBase
{
    public BuffConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (BuffEnum)_buf["id"].AsInt; }
        { if(!_buf["target_type"].IsNumber) { throw new SerializationException(); }  TargetType = (BuffTargetTypeEnum)_buf["target_type"].AsInt; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (BuffType)_buf["type"].AsInt; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["only_in_battle"].IsBoolean) { throw new SerializationException(); }  OnlyInBattle = _buf["only_in_battle"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static BuffConfig DeserializeBuffConfig(JSONNode _buf)
    {
        return new BuffConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly BuffEnum Id;
    /// <summary>
    /// 目标
    /// </summary>
    public readonly BuffTargetTypeEnum TargetType;
    public readonly BuffType Type;
    /// <summary>
    /// 名字(不填从id解析)
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 是否只在战斗中存在
    /// </summary>
    public readonly bool OnlyInBattle;
    /// <summary>
    /// 效果描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -1370631787;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "targetType:" + TargetType + ","
        + "type:" + Type + ","
        + "name:" + Name + ","
        + "onlyInBattle:" + OnlyInBattle + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}
