
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class BuffTable
{
    private readonly System.Collections.Generic.Dictionary<BuffEnum, BuffConfig> _dataMap;
    private readonly System.Collections.Generic.List<BuffConfig> _dataList;
    
    public BuffTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<BuffEnum, BuffConfig>();
        _dataList = new System.Collections.Generic.List<BuffConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BuffConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = BuffConfig.DeserializeBuffConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<BuffEnum, BuffConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BuffConfig> DataList => _dataList;

    public BuffConfig GetOrDefault(BuffEnum key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuffConfig Get(BuffEnum key) => _dataMap[key];
    public BuffConfig this[BuffEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

