
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BuffTargetTypeEnum
    {
        我方单体 = 0,
        我方全体 = 1,
        敌方单体 = 2,
        敌方全体 = 3,
        我方部分 = 4,
        敌人部分 = 5,
        敌我全体 = 6,
        敌我部分 = 7,
    }

} 

