
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BuffEnum
    {
        测试0 = 0,
        易损 = 1,
        暴虐 = 2,
        吸血 = 3,
        肉质 = 4,
        寄生 = 5,
        灼伤 = 6,
        储藏 = 7,
        升级 = 8,
        神经毒素 = 9,
        高额伤害 = 10,
    }

} 

