
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BuffEnum
    {
        测试0 = 0,
        易损 = 1,
        暴虐 = 2,
        吸血 = 3,
        肉质 = 4,
        寄生 = 5,
        灼伤 = 6,
        储藏 = 7,
        升级 = 8,
        神经毒素 = 9,
        高额伤害 = 10,
        永久速度 = 11,
        永久固定防御力 = 12,
        永久固定力量 = 13,
        永久固定生命值 = 14,
        临时固定速度 = 15,
        临时固定力量 = 16,
        临时固定防御 = 17,
        恢复百分比生命 = 18,
        受到固定真实伤害 = 19,
        下次攻击伤害倍率 = 20,
        降低百分比力量 = 21,
    }

} 

