
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class BuildingCardTable
{
    private readonly System.Collections.Generic.Dictionary<ItemEnum, BuildingCardConfig> _dataMap;
    private readonly System.Collections.Generic.List<BuildingCardConfig> _dataList;
    
    public BuildingCardTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<ItemEnum, BuildingCardConfig>();
        _dataList = new System.Collections.Generic.List<BuildingCardConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BuildingCardConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = BuildingCardConfig.DeserializeBuildingCardConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<ItemEnum, BuildingCardConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BuildingCardConfig> DataList => _dataList;

    public BuildingCardConfig GetOrDefault(ItemEnum key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BuildingCardConfig Get(ItemEnum key) => _dataMap[key];
    public BuildingCardConfig this[ItemEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

