
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class CardIndexTable
{
    private readonly System.Collections.Generic.Dictionary<ItemEnum, CardIndex> _dataMap;
    private readonly System.Collections.Generic.List<CardIndex> _dataList;
    
    public CardIndexTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<ItemEnum, CardIndex>();
        _dataList = new System.Collections.Generic.List<CardIndex>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CardIndex _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CardIndex.DeserializeCardIndex(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<ItemEnum, CardIndex> DataMap => _dataMap;
    public System.Collections.Generic.List<CardIndex> DataList => _dataList;

    public CardIndex GetOrDefault(ItemEnum key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CardIndex Get(ItemEnum key) => _dataMap[key];
    public CardIndex this[ItemEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

