
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class EffectCardTable
{
    private readonly System.Collections.Generic.Dictionary<ItemEnum, EffectCardConfig> _dataMap;
    private readonly System.Collections.Generic.List<EffectCardConfig> _dataList;
    
    public EffectCardTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<ItemEnum, EffectCardConfig>();
        _dataList = new System.Collections.Generic.List<EffectCardConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EffectCardConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = EffectCardConfig.DeserializeEffectCardConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<ItemEnum, EffectCardConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<EffectCardConfig> DataList => _dataList;

    public EffectCardConfig GetOrDefault(ItemEnum key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EffectCardConfig Get(ItemEnum key) => _dataMap[key];
    public EffectCardConfig this[ItemEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

