
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class EffectCardConfig : Luban.BeanBase
{
    public EffectCardConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (ItemEnum)_buf["id"].AsInt; }
        { if(!_buf["needTarget"].IsBoolean) { throw new SerializationException(); }  NeedTarget = _buf["needTarget"]; }
    }

    public static EffectCardConfig DeserializeEffectCardConfig(JSONNode _buf)
    {
        return new EffectCardConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly ItemEnum Id;
    /// <summary>
    /// 是否拖到某个目标上使用
    /// </summary>
    public readonly bool NeedTarget;
   
    public const int __ID__ = -1524549885;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "needTarget:" + NeedTarget + ","
        + "}";
    }
}

}
