
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class EnemyPowerConfig : Luban.BeanBase
{
    public EnemyPowerConfig(JSONNode _buf) 
    {
        { if(!_buf["idx"].IsNumber) { throw new SerializationException(); }  Idx = _buf["idx"]; }
    }

    public static EnemyPowerConfig DeserializeEnemyPowerConfig(JSONNode _buf)
    {
        return new EnemyPowerConfig(_buf);
    }

    /// <summary>
    /// 第几圈
    /// </summary>
    public readonly int Idx;
   
    public const int __ID__ = 402323487;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
    }

    public override string ToString()
    {
        return "{ "
        + "idx:" + Idx + ","
        + "}";
    }
}

}
