
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class EnemyPowerTable
{
    private readonly System.Collections.Generic.Dictionary<int, EnemyPowerConfig> _dataMap;
    private readonly System.Collections.Generic.List<EnemyPowerConfig> _dataList;
    
    public EnemyPowerTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, EnemyPowerConfig>();
        _dataList = new System.Collections.Generic.List<EnemyPowerConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            EnemyPowerConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = EnemyPowerConfig.DeserializeEnemyPowerConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Idx, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, EnemyPowerConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<EnemyPowerConfig> DataList => _dataList;

    public EnemyPowerConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public EnemyPowerConfig Get(int key) => _dataMap[key];
    public EnemyPowerConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

