
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    [System.Flags]
    public enum EntityTypeEnum
    {
        /// <summary>
        /// 这里是二进制
        /// </summary>
        None = 0,
        Pokemon = 1,
        Building = 2,
        Terrain = 4,
    }

} 

