
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum GroupEnum
    {
        None = 0,
        All = 1,
        友方 = 2,
        敌方 = 3,
    }

} 

