
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (ItemEnum)_buf["id"].AsInt; }
        { if(!_buf["name"].IsNumber) { throw new SerializationException(); }  Name = (ItemTypeEnum)_buf["name"].AsInt; }
    }

    public static ItemConfig DeserializeItemConfig(JSONNode _buf)
    {
        return new ItemConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly ItemEnum Id;
    /// <summary>
    /// 名字(不填从id解析)
    /// </summary>
    public readonly ItemTypeEnum Name;
   
    public const int __ID__ = -764023723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "}";
    }
}

}
