
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemCardConfig : Luban.BeanBase
{
    public ItemCardConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (ItemEnum)_buf["id"].AsInt; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (CardTypeEnum)_buf["type"].AsInt; }
    }

    public static ItemCardConfig DeserializeItemCardConfig(JSONNode _buf)
    {
        return new ItemCardConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly ItemEnum Id;
    public readonly string Name;
    public readonly string Description;
    public readonly CardTypeEnum Type;
   
    public const int __ID__ = 1813251589;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "type:" + Type + ","
        + "}";
    }
}

}
