
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    public ItemConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (ItemEnum)_buf["id"].AsInt; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (ItemTypeEnum)_buf["type"].AsInt; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["max_stack"].IsNumber) { throw new SerializationException(); }  MaxStack = _buf["max_stack"]; }
    }

    public static ItemConfig DeserializeItemConfig(JSONNode _buf)
    {
        return new ItemConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly ItemEnum Id;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly ItemTypeEnum Type;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 最大堆叠数量
    /// </summary>
    public readonly short MaxStack;
   
    public const int __ID__ = -764023723;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "desc:" + Desc + ","
        + "maxStack:" + MaxStack + ","
        + "}";
    }
}

}
