
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class ItemCardTable
{
    private readonly System.Collections.Generic.Dictionary<ItemEnum, ItemCardConfig> _dataMap;
    private readonly System.Collections.Generic.List<ItemCardConfig> _dataList;
    
    public ItemCardTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<ItemEnum, ItemCardConfig>();
        _dataList = new System.Collections.Generic.List<ItemCardConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ItemCardConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = ItemCardConfig.DeserializeItemCardConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<ItemEnum, ItemCardConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ItemCardConfig> DataList => _dataList;

    public ItemCardConfig GetOrDefault(ItemEnum key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ItemCardConfig Get(ItemEnum key) => _dataMap[key];
    public ItemCardConfig this[ItemEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

