
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ItemEnum
    {
        大森林 = 0,
        矿山 = 1,
        墓园 = 2,
        战斗哨塔 = 3,
        废铁厂 = 4,
        高速升级 = 5,
        装甲升级 = 6,
        重组升级 = 7,
        能量饮料 = 8,
        脏拖把 = 9,
    }

} 

