
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum PassiveEnum
    {
        None = 0,
        Evolution = 1,
        Collecting = 2,
        SpreadSeed = 3,
        HugeWeapon = 4,
        Loyalty = 5,
        SuperSpeed = 6,
        捡拾 = 7,
        水晶诅咒 = 8,
        常规机械 = 9,
        枯木逢春 = 10,
        高温 = 11,
        下毒 = 12,
        大口吃 = 13,
        一刀斩 = 14,
        屯屯 = 15,
        仇恨滔天 = 16,
        猛毒 = 17,
        负重前行 = 18,
    }

} 

