
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class PassiveTable
{
    private readonly System.Collections.Generic.Dictionary<PassiveEnum, PassiveConfig> _dataMap;
    private readonly System.Collections.Generic.List<PassiveConfig> _dataList;
    
    public PassiveTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<PassiveEnum, PassiveConfig>();
        _dataList = new System.Collections.Generic.List<PassiveConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PassiveConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = PassiveConfig.DeserializePassiveConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<PassiveEnum, PassiveConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<PassiveConfig> DataList => _dataList;

    public PassiveConfig GetOrDefault(PassiveEnum key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PassiveConfig Get(PassiveEnum key) => _dataMap[key];
    public PassiveConfig this[PassiveEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

