
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum PassiveEnum
    {
        None = 0,
        Evolution = 1,
        Collecting = 2,
        SpreadSeed = 3,
        HugeWeapon = 4,
        Loyalty = 5,
        SuperSpeed = 6,
    }

} 

