
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PokemonConfig : Luban.BeanBase
{
    public PokemonConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (PokemonEnum)_buf["id"].AsInt; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (PokemonTypeEnum)_buf["type"].AsInt; }
        { if(!_buf["passive"].IsNumber) { throw new SerializationException(); }  Passive = (PassiveEnum)_buf["passive"].AsInt; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["elementA"].IsNumber) { throw new SerializationException(); }  ElementA = (ElementEnum)_buf["elementA"].AsInt; }
        { if(!_buf["elementB"].IsNumber) { throw new SerializationException(); }  ElementB = (ElementEnum)_buf["elementB"].AsInt; }
        { if(!_buf["raceA"].IsNumber) { throw new SerializationException(); }  RaceA = (RaceEnum)_buf["raceA"].AsInt; }
        { if(!_buf["raceB"].IsNumber) { throw new SerializationException(); }  RaceB = (RaceEnum)_buf["raceB"].AsInt; }
        { if(!_buf["lv1_hp"].IsNumber) { throw new SerializationException(); }  Lv1Hp = _buf["lv1_hp"]; }
        { if(!_buf["lv2_hp"].IsNumber) { throw new SerializationException(); }  Lv2Hp = _buf["lv2_hp"]; }
        { if(!_buf["lv3_hp"].IsNumber) { throw new SerializationException(); }  Lv3Hp = _buf["lv3_hp"]; }
        { if(!_buf["lv4_hp"].IsNumber) { throw new SerializationException(); }  Lv4Hp = _buf["lv4_hp"]; }
        { if(!_buf["lv5_hp"].IsNumber) { throw new SerializationException(); }  Lv5Hp = _buf["lv5_hp"]; }
        { if(!_buf["lv1_atk"].IsNumber) { throw new SerializationException(); }  Lv1Atk = _buf["lv1_atk"]; }
        { if(!_buf["lv2_atk"].IsNumber) { throw new SerializationException(); }  Lv2Atk = _buf["lv2_atk"]; }
        { if(!_buf["lv3_atk"].IsNumber) { throw new SerializationException(); }  Lv3Atk = _buf["lv3_atk"]; }
        { if(!_buf["lv4_atk"].IsNumber) { throw new SerializationException(); }  Lv4Atk = _buf["lv4_atk"]; }
        { if(!_buf["lv5_atk"].IsNumber) { throw new SerializationException(); }  Lv5Atk = _buf["lv5_atk"]; }
        { if(!_buf["lv1_def"].IsNumber) { throw new SerializationException(); }  Lv1Def = _buf["lv1_def"]; }
        { if(!_buf["lv2_def"].IsNumber) { throw new SerializationException(); }  Lv2Def = _buf["lv2_def"]; }
        { if(!_buf["lv3_def"].IsNumber) { throw new SerializationException(); }  Lv3Def = _buf["lv3_def"]; }
        { if(!_buf["lv4_def"].IsNumber) { throw new SerializationException(); }  Lv4Def = _buf["lv4_def"]; }
        { if(!_buf["lv5_def"].IsNumber) { throw new SerializationException(); }  Lv5Def = _buf["lv5_def"]; }
        { if(!_buf["lv1_speed"].IsNumber) { throw new SerializationException(); }  Lv1Speed = _buf["lv1_speed"]; }
        { if(!_buf["lv2_speed"].IsNumber) { throw new SerializationException(); }  Lv2Speed = _buf["lv2_speed"]; }
        { if(!_buf["lv3_speed"].IsNumber) { throw new SerializationException(); }  Lv3Speed = _buf["lv3_speed"]; }
        { if(!_buf["lv4_speed"].IsNumber) { throw new SerializationException(); }  Lv4Speed = _buf["lv4_speed"]; }
        { if(!_buf["lv5_speed"].IsNumber) { throw new SerializationException(); }  Lv5Speed = _buf["lv5_speed"]; }
        { if(!_buf["lv1_adap"].IsNumber) { throw new SerializationException(); }  Lv1Adap = _buf["lv1_adap"]; }
        { if(!_buf["lv2_adap"].IsNumber) { throw new SerializationException(); }  Lv2Adap = _buf["lv2_adap"]; }
        { if(!_buf["lv3_adap"].IsNumber) { throw new SerializationException(); }  Lv3Adap = _buf["lv3_adap"]; }
        { if(!_buf["lv4_adap"].IsNumber) { throw new SerializationException(); }  Lv4Adap = _buf["lv4_adap"]; }
        { if(!_buf["lv5_adap"].IsNumber) { throw new SerializationException(); }  Lv5Adap = _buf["lv5_adap"]; }
    }

    public static PokemonConfig DeserializePokemonConfig(JSONNode _buf)
    {
        return new PokemonConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly PokemonEnum Id;
    /// <summary>
    /// 名字(不填从id解析)
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 类型
    /// </summary>
    public readonly PokemonTypeEnum Type;
    /// <summary>
    /// 特点
    /// </summary>
    public readonly PassiveEnum Passive;
    /// <summary>
    /// 特点描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly ElementEnum ElementA;
    /// <summary>
    /// 属性
    /// </summary>
    public readonly ElementEnum ElementB;
    public readonly RaceEnum RaceA;
    public readonly RaceEnum RaceB;
    /// <summary>
    /// 1级生命
    /// </summary>
    public readonly int Lv1Hp;
    /// <summary>
    /// 2级生命
    /// </summary>
    public readonly int Lv2Hp;
    /// <summary>
    /// 3级生命
    /// </summary>
    public readonly int Lv3Hp;
    /// <summary>
    /// 4级生命
    /// </summary>
    public readonly int Lv4Hp;
    /// <summary>
    /// 5级生命
    /// </summary>
    public readonly int Lv5Hp;
    /// <summary>
    /// 1级力量
    /// </summary>
    public readonly int Lv1Atk;
    /// <summary>
    /// 2级力量
    /// </summary>
    public readonly int Lv2Atk;
    /// <summary>
    /// 3级力量
    /// </summary>
    public readonly int Lv3Atk;
    /// <summary>
    /// 4级力量
    /// </summary>
    public readonly int Lv4Atk;
    /// <summary>
    /// 5级力量
    /// </summary>
    public readonly int Lv5Atk;
    /// <summary>
    /// 1级防御
    /// </summary>
    public readonly int Lv1Def;
    /// <summary>
    /// 2级防御
    /// </summary>
    public readonly int Lv2Def;
    /// <summary>
    /// 3级防御
    /// </summary>
    public readonly int Lv3Def;
    /// <summary>
    /// 4级防御
    /// </summary>
    public readonly int Lv4Def;
    /// <summary>
    /// 5级防御
    /// </summary>
    public readonly int Lv5Def;
    /// <summary>
    /// 1级速度
    /// </summary>
    public readonly int Lv1Speed;
    /// <summary>
    /// 2级速度
    /// </summary>
    public readonly int Lv2Speed;
    /// <summary>
    /// 3级速度
    /// </summary>
    public readonly int Lv3Speed;
    /// <summary>
    /// 4级速度
    /// </summary>
    public readonly int Lv4Speed;
    /// <summary>
    /// 5级速度
    /// </summary>
    public readonly int Lv5Speed;
    /// <summary>
    /// 1级适应
    /// </summary>
    public readonly int Lv1Adap;
    /// <summary>
    /// 2级适应
    /// </summary>
    public readonly int Lv2Adap;
    /// <summary>
    /// 3级适应
    /// </summary>
    public readonly int Lv3Adap;
    /// <summary>
    /// 4级适应
    /// </summary>
    public readonly int Lv4Adap;
    /// <summary>
    /// 5级适应
    /// </summary>
    public readonly int Lv5Adap;
   
    public const int __ID__ = -622808619;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "passive:" + Passive + ","
        + "desc:" + Desc + ","
        + "elementA:" + ElementA + ","
        + "elementB:" + ElementB + ","
        + "raceA:" + RaceA + ","
        + "raceB:" + RaceB + ","
        + "lv1Hp:" + Lv1Hp + ","
        + "lv2Hp:" + Lv2Hp + ","
        + "lv3Hp:" + Lv3Hp + ","
        + "lv4Hp:" + Lv4Hp + ","
        + "lv5Hp:" + Lv5Hp + ","
        + "lv1Atk:" + Lv1Atk + ","
        + "lv2Atk:" + Lv2Atk + ","
        + "lv3Atk:" + Lv3Atk + ","
        + "lv4Atk:" + Lv4Atk + ","
        + "lv5Atk:" + Lv5Atk + ","
        + "lv1Def:" + Lv1Def + ","
        + "lv2Def:" + Lv2Def + ","
        + "lv3Def:" + Lv3Def + ","
        + "lv4Def:" + Lv4Def + ","
        + "lv5Def:" + Lv5Def + ","
        + "lv1Speed:" + Lv1Speed + ","
        + "lv2Speed:" + Lv2Speed + ","
        + "lv3Speed:" + Lv3Speed + ","
        + "lv4Speed:" + Lv4Speed + ","
        + "lv5Speed:" + Lv5Speed + ","
        + "lv1Adap:" + Lv1Adap + ","
        + "lv2Adap:" + Lv2Adap + ","
        + "lv3Adap:" + Lv3Adap + ","
        + "lv4Adap:" + Lv4Adap + ","
        + "lv5Adap:" + Lv5Adap + ","
        + "}";
    }
}

}
