
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class PokemonTable
{
    private readonly System.Collections.Generic.Dictionary<PokemonEnum, PokemonConfig> _dataMap;
    private readonly System.Collections.Generic.List<PokemonConfig> _dataList;
    
    public PokemonTable(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<PokemonEnum, PokemonConfig>();
        _dataList = new System.Collections.Generic.List<PokemonConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PokemonConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = PokemonConfig.DeserializePokemonConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<PokemonEnum, PokemonConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<PokemonConfig> DataList => _dataList;

    public PokemonConfig GetOrDefault(PokemonEnum key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PokemonConfig Get(PokemonEnum key) => _dataMap[key];
    public PokemonConfig this[PokemonEnum key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

