
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum PokemonEnum
    {
        玩家 = 0,
        灯笼鬼 = 1,
        小幽魂 = 2,
        笨笨甲熊 = 3,
        枯木妖 = 4,
        烈火领主 = 5,
        落叶蝴蝶 = 6,
        一口鲸 = 7,
        铁刀客 = 8,
        围巾狸 = 9,
        研究体0号 = 10,
        猛毒蝎 = 11,
        负树龟 = 12,
    }

} 

