
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum RaceEnum
    {
        None = 0,
        Ghost = 1,
        Spirit = 2,
        Animal = 3,
        Plant = 4,
        Robot = 5,
        Insect = 6,
    }

} 

