
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TerrainCardConfig : Luban.BeanBase
{
    public TerrainCardConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = (ItemEnum)_buf["id"].AsInt; }
    }

    public static TerrainCardConfig DeserializeTerrainCardConfig(JSONNode _buf)
    {
        return new TerrainCardConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly ItemEnum Id;
   
    public const int __ID__ = 311021415;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "}";
    }
}

}
